#!/usr/bin/env python3

# Any probabilities are 1 in n

BASE_YEAR = 1443
# change according to probability
PROFESSIONS = ["farmer"]*2 + ["merchant"]

GENDERS = ["male", "female"]
ATTRIBUTES = ["o", "c", "e", "a", "n", "p", "i"]
CAP_CUTOFF = 3.5
LIFE_EXPECTANCY = 40*4
# standard deviation for life expectancy random gaussian distribution
LIFE_EXPECTANCY_SD = 5*4
GEN_ATTR_SD = 0.2

START_CHILDREN_MAX_AGE = 12*4
START_RELATIVE_RAPPORT = 0.7

ATTRIBUTE_CHANGE = 0.2
ATTRIBUTE_CHANGE_AGE = 50*4

HARSH_WINTER_CHANCE = 4
HARSH_WINTER_MOD = 0.5

YIELD_MOD_MIN = 0.8
YIELD_MOD_MAX = 1.2
YIELD_MOD_SD = 0.1

WORKING_CHILD_MIN_AGE = 8*4

ADULT_FOOD_NOURISHED = 10
ADULT_FOOD_HUNGRY = 7
ADULT_FOOD_MALNOURISHED = 4

CHILD_FOOD_NOURISHED = 6
CHILD_FOOD_HUNGRY = 4
CHILD_FOOD_MALNOURISHED = 2

ADULT_BASE_HARVEST = 50
CHILD_BASE_HARVEST = 25

MERCHANT_BASE_INCOME = 15

MAX_FOOD_STORAGE_PER_PERSON = 100

ROM_INTEREST_THRESH_BASE = 5

RAPPORT_DECAY = 0.05

SUICIDE_MIN_MOOD_LEVEL = -1.5

START_INTERACTION_MIN_AGE = 3*4
DT_CHANCE = 3
DT_RAPPORT_GAIN = 0.09
DT_MIN_AGE = 8*4
CHAT_RAPPORT_GAIN = 0.03
ARGUMENT_RAPPORT_GAIN = -0.05
ANGRY_LOOK_RAPPORT_GAIN = -0.03
CAP_MODIFIER = 4  # divided by
MIN_ASKOUT_AGE = 16*4

MIN_ARGUMENT_AGE = 5*4

# Modifier applied to rapport if someone else initiated
# the interaction.
INTERACTED_WITH_MOD = (2/3)

FRIEND_THRESHOLD = 0.5
BEST_FRIEND_THRESHOLD = 0.8

# Minimum time spent together before marriage
BASE_MARRIAGE_MIN_TIME = 6
MARRIAGE_MIN_AGE = 18*4

TAKE_NEW_NAME = False

BABY_MAX_AMOUNT = 6
BASE_BABY_CHANCE = 15

MIN_ARMY_AGE = 21*4
MAX_ARMY_AGE = 26*4
MAX_ARMY_FRIENDS = 2
MAX_ARMY_BEST_FRIENDS = 1
BASE_ARMY_CHANCE = 5  # must be > 2

COMMUNITY_FAMILY_LIMIT = 10
ATTACK_KILL_AMOUNT = 4

COMMUNITY_FAMILY_MIN = 3
COMMUNITY_FAMILY_JOIN = 2

ELECTION_SEASON = 0
MAYOR_TERM_LENGTH = 4*4
MIN_MAYOR_AGE = 18*4
MIN_VOTING_AGE = 16*4
RAPPORT_VOTING_MODIFIER = (1/4)
MAYOR_INTERACTIONS_MOD = 1.5
